"""updated users table

Revision ID: 8ec9b8128e40
Revises: 734f853971bf
Create Date: 2026-05-11 15:58:31.852102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec9b8128e40'
down_revision: Union[str, Sequence[str], None] = '734f853971bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_name_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_name_key'), 'users', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
